### ISSUE TITLE
DEPRECATION WARNING: Initialization autoloaded the constants on Rails 6.1.4

### ISSUE THREAD

**Issue by carrabi** [RIPAGlobal/scimitar#12]
Hey All,

Great gem. It's saved me a  ton of time.  Heads up, running rspec throws a depreciation warning. See  below

`DEPRECATION WARNING: Initialization autoloaded the constants Scimitar::ServiceProviderConfiguration, Scimitar::Supportable, Scimitar::Filter, Scimitar::Meta, Scimitar::AuthenticationScheme, and Scimitar::EngineConfiguration.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload Scimitar::ServiceProviderConfiguration, for example,
the expected changes won't be reflected in that stale Class object.

These autoloaded constants have been unloaded.`

**Comment by carrabi** [comment]
I figured it out. I need to add the following to my `spec_helper.rb`

```
require 'active_model'

gem_dir = Gem::Specification.find_by_name('scimitar').gem_dir

require "#{gem_dir}/app/models/scimitar/supportable"
require "#{gem_dir}/app/models/scimitar/filter"
require "#{gem_dir}/app/models/scimitar/meta"
require "#{gem_dir}/app/models/scimitar/authentication_scheme"
require "#{gem_dir}/app/models/scimitar/engine_configuration"
require "#{gem_dir}/app/models/scimitar/service_provider_configuration"
```

**Comment by eapache-opslevel** [comment]
We are also seeing this. Adding a bunch of manual `requires` to the test helper is a workaround, but it seems like there must be some other incompatibility at play? We don't have to do this for any of our other gems...

**Comment by carrabi** [comment]
@eapache-opslevel Agreed. It was a workaround. The latest version of the gem fixed the issue for us. Note - We have migrated to rails 7, ruby 3

**Comment by eapache-opslevel** [comment]
Ah, ok, I'll revisit then when we migrate to rails 7.

**Comment by pond** [comment]
This is possibly because an older Scimitar initializer in your `config/initializers` folder is addressing `Scimitar` constants directly and it sounds like this is now being warned about in Rails 6, as well as being something we saw (at the time) only when we were moving to Rails 6. See this reference:

* https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-when-the-application-boots

...which is why the current Scimitar gems use the pattern suggested above in their template configuration:

```ruby
Rails.application.config.to_prepare do
  Scimitar.service_provider_configuration = ...
  Scimitar.engine_configuration = ...
end
```

If you want to avoid warnings while still on older Rails and/or gems, try adding the `Rails.application.config.to_prepare do...end` to your Scimitar initializer and see if that prevents the deprecation warnings.

**Comment by eapache-opslevel** [comment]
In fact our SCIM initializer is already wrapped in `to_prepare` and we see the deprecation warnings even in that case. It's odd because that was the suitable fix in other cases we ran across, but it didn't work for scimitar. I'm really not sure why this is happening, but FWIW the workaround posted by @carrabi does "fix" it for us.

We're specifically seeing this on scimitar v1.3.0, rails v6.1.6.1.
