### ISSUE TITLE
require_scim is problematic with Azure AD

### ISSUE THREAD

**Issue by kwent** [RIPAGlobal/scimitar#20]
## require_scim is problematic with Azure AD

See https://github.com/MicrosoftDocs/azure-docs/issues/94189

My workaround for now: https://github.com/rootlyhq/scimitar/commit/2de2572b9f5a121dd9a63f029635b241280a0442

Wonder if there is a cleaner solution ?

Regards

**Comment by pond** [comment]
Thanks for the report & links to the issues - very useful. I've created https://github.com/RIPAGlobal/scimitar/pull/21 (currently under code review) which, if the comments made on the Azure AD ticket are correct, ought to fix things - I'll update this ticket once that gem version is pushed, so you can give it a try (or you could try applying the PR's diff to your local copy & test there in advance if you wish).

**Comment by pond** [comment]
V2.0.2 which _hopefully_ fixes the issue is now published (https://rubygems.org/gems/scimitar).

**Comment by pond** [comment]
@kwent Please do let me know via this ticket if things look to be fixed in v2.0.2 - I'll close the ticket if so, else we'll work out next steps to try and fix up things for Azure AD.

We developed this gem originally with an Azure AD client in mind, but in practice they ended up (partly, the ol' Covid reasons) not enabling that particular integration. So far, we've never actually had a "real" Azure AD caller come in - so your experience & bug report is very helpful.

**Comment by kwent** [comment]
@pond will do ! Just need to port over your changes in my branch cause i'm still running on rails 6.0

**Comment by pond** [comment]
Ah, yes. Fair. Would it help if I back-ported the fix onto the 1.x gem series?

**Comment by kwent** [comment]
It would speed up the process for sure !

**Comment by pond** [comment]
@kwent Well, assuming I didn't mess it up - I've not tried going back in time with Git tags & gem pushes before! - then https://rubygems.org/gems/scimitar is showing v1.2.1, which back-ports v2.0.1 and v2.0.2's fixes.

**Comment by kwent** [comment]
@pond confirming that fixes the issue ! Thank you for your help so much :)

**Comment by pond** [comment]
That's great! Thanks for the issue & feedback.
