### ISSUE TITLE
Error when trying to use version 1.3.1 - undefined method  `read_attribute_for_serialization`

### ISSUE THREAD

**Issue by yasuf** [RIPAGlobal/scimitar#34]
Hey,

I'm running into an error when testing the `get :show` method on a controller:

```
From: /Users/yasu/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/scimitar-1.3.1/app/controllers/scimitar/resources_controller.rb:66 Scimitar::ResourcesController#show:

    63: def show(&block)
    64:   scim_resource = yield(self.safe_params()[:id])
    65:   binding.pry
 => 66:   render(json: scim_resource)
    67: end

[onboardiq][TEST]> render(json: scim_resource)
NoMethodError: undefined method `read_attribute_for_serialization' for #<Scimitar::Resources::User:0x000000012ece8ab8>
```

I can't find how this `render(json: scim_resource)` is calling `read_attribute_for_serialization`.

This is our test file:

```ruby
describe ScimV2::ScimUsersController do
  let(:parsed_response) { JSON.parse(response.body, symbolize_names: true) }
  let!(:user) { create(:user) }

  context 'GET show' do
    it 'renders the resource' do
      get :show, params: { id: user.id, format: :scim }
      expect(response.status).to eq(200)
      expect(parsed_response()).to include(id: user.id)
    end
  end
end
```

We have some more code to add a token in the test but I don't think it's relevant for the error we're getting.

Versions:
Rails version: 6.1.7
Ruby version: 2.7.5

**Comment by pond** [comment]
We aren't generally able as gem maintainers to provide debugging services for third party code, especially in your tests. If your feature works fine when it's driven in your web site directly, then the issue is with your test code / test setup and you'll have to figure that out yourself.

The error message you describe most likely comes from down in Rails somewhere, but you provide no backtrace, so it's impossible to say. If you can at least give the full backtrace, it might help with diagnosis.

**Comment by yasuf** [comment]
when overriding the `show` method in `Scimitar::ResourcesController` with this:
```
    def show
      user = find_user(params[:id])
      scim_user = user.to_scim(location: url_for(action: :show, id: user.id))
      render(json: scim_user.as_json)
    end
```

the render started working fine, does the gem need to call `.as_json` in that show method? This is what's currently in 1.3.1:
```
    def show(&block)
      scim_resource = yield(self.safe_params()[:id])™
      render(json: scim_resource)
    end
```

**Comment by pond** [comment]
It would depend on the resource. You're using the _low level_ non-ActiveRecord controller - else you'd have subclassed and used the automatics in `Scimitar::ActiveRecordBackedResourcesController` and needed quite a lot less code. Since this therefore assuming that you are probably _not_ using ActiveRecord, it cannot assume that your returned resource has any such method as `#as_json` applied and is assuming that the object "does the right thing" when Rails attempts the render.

So there are I guess a couple of options - just use your override; implement `#as_json` in whatever class your `user` is; or I suppose I _could_ try and do an `if respond_to?(:as_json)` check, but the curious thing is that I didn't expect it would be needed since Rails and things like Hashes or ActiveRecord objects in the context of `render json: <foo>` usually just "do the right thing"; I'd worry that forcing `#as_json` calls in might disturb more things than it fixes. Even so, that's an option.

**Comment by bettysteger** [comment]
In case someone comes back here, I had the same error because i have ActiveModel::Serializer enabled and it always tried to  convert `Scimitar::Resources::User` with the `UserSerializer`:

```
Rendered UserSerializer with ActiveModelSerializers::Adapter::Attributes (2.29ms)
undefined method `read_attribute_for_serialization' for #<Scimitar::Resources::User:
```

My fix was overwriting the render method to disable the serializer (with adapter: nil) for the whole controller:

```ruby
  # need this to prevent 'read_attribute_for_serialization' error and disable the Serializer
  def render(*args)
    options = args.extract_options!
    options[:adapter] = nil
    args << options
    super(*args)
  end
  ```

**Comment by paulodeon** [comment]
I also had this problem and @bettysteger's solution helped me. In my case it was the `active_model_serializers` gem which was causing the problem. I was inheriting from `Scimitar::ResourcesController ` and ended up overriding the create method to call the `to_json` method on the object, rather than passing it directly to `render :json` which would use the app's user serializer:

```ruby
    def create
      with_scim_resource() do |resource|
        result = self.storage_class().transaction do
          record = self.new_storage_record()
          record.from_scim!(scim_hash: resource.as_json())
          self.save!(record)
          record_to_scim(record)
        end

        render(json: result.to_json, status: :created)
      end
    end
 ```

**Comment by paulodeon** [comment]
Having then found I'd need to do that across all actions I found a better solution which is just to override this method in the controller:
```ruby
def default_serializer_options
  { serializer: nil }
end
```
