### ISSUE TITLE
Potential to yield record in ActiveRecordBackedResourcesController

### ISSUE THREAD

**Issue by wooly** [RIPAGlobal/scimitar#60]
Would it be possible to add block support to the `ActiveRecordBackedResourcesController` to allow the injection of custom code _before_ the record is saved for the create (and potentially replace/update as well) actions.

Something like this:

```ruby
def create
  super do |scim_resource|
    self.storage_class().transaction do
    record = self.storage_class().new
    record.from_scim!(scim_hash: scim_resource.as_json())
    yield record if block_given?
    self.save!(record)
    record_to_scim(record)
  end
end
```

This would then allow us to define our users controller like follows:

```ruby
def create
  super do |user|   
    user.accepted_terms_and_conditions = true
  end
end
```

Instead of having to fully sub-class and inherit from `ResourcesController`.

Unless is there another way to pass through custom functionality like this that I haven't seen?

Thanks!

**Comment by xjunior** [comment]
Have you tried using AR callbacks or anyway from the model?

I'm using Scimitar, and I've been able to successfully implement all of my customizations this way, which leads to a better code in the end

**Comment by xjunior** [comment]
@wooly can this be achieved through `before_save {  self.accepted_terms_and_conditions = true }`?

**Comment by eduardoborba** [comment]
In my case, it wouldn't be possible, because the User records could be created in different ways and not only through the SCIM provisioning. And I would like to set some of the variables only when setting up through SCIM.

Other than that, there is a case that is a bit more complex where I set the `company_id` based on my authentication service (that is using JWT to identify which company is authenticating). Something like this:

```
def create
  super do |user|   
    user.company_id = AuthenticationService.company_id
  end
end
```

**Comment by wooly** [comment]
I have similar requirements to @eduardoborba around calling out to external services to send welcome emails and orchestrating the creation of has_many through records for organisation ‘memberships’ which I would rather do at the controller level than in model callbacks.

I’ve worked around it for now by coping the AR backed resources controller and modifying it for my needs, but feel that yielding might also be useful.

**Comment by xjunior** [comment]
You could also:
- subclass your model and have this specific subclass to deal with the SCIM specific creation there;
- or wrap it in a `SimpleDelegator`

Both solutions would:
- maintain the ActiveRecord API that required by `ActiveRecordBackedResourcesController`, allowing you to use it without modifications
- give you control to switch between the behaviors you want (by using either `User` or `ScimUser`)
- unit test these behaviors
-

**Comment by pond** [comment]
It seems that all the suggestions here offer a plethora of largely Rails/ActiveRecord-orientated ways to do the kind of thing you want to do. I wouldn't be in a hurry to extend Scimitar unless there's a use case beyond that which I'm missing - so - did you manage to implement a solution based on the suggestions above, or are you still stuck?

**Comment by gsar** [comment]
@wooly @eduardoborba it seems the `save!` method can be overridden (in a similar way as `destroy` can be) to achieve what you want, as that is called by `create`, `replace`, and `update`.

``` ruby
class Scim::UsersController < Scimitar::ActiveRecordBackedResourcesController
  def destroy
    super do |user|
      user.soft_delete
    end
  end

  protected

  def save!(record)
    super(record) do |user|
      if user.persisted?
        # update / replace extra bits here
      else
        # create extra bits
        user.company = current_company
        user.skip_confirmation!
      end
      user.save!
    end
  end
end
```

**Comment by rjclaasen** [comment]
I also have similar requirements to @eduardoborba, where I'd like to be able to set a configuration_id on the created user depending on the authorization header like so:

```ruby
class Scim::UsersController < Scimitar::ActiveRecordBackedResourcesController
  def create
    super do |user|
      user.sso_configuration_id = current_organisation.sso_configuration_id
    end
  end

  private

  def current_organisation
    token = request.headers['Authorization']
    external_id = JWT.decode(token).first['issuer']
    Organisation.find_by(external_id: external_id)
  end
end
```

@xjunior @pond How could I use lifecycle hooks to set the correct configuration_id? As far as I'm aware, the model instance does not have any knowledge of the request's headers, so it would be difficult to determine which configuration_id to set.

What would be the disadvantages of extending Scimitar in a way where records can be yielded to allow for code injection during record updates?

**Comment by pond** [comment]
It seems to me that:

* `Scimitar::ActiveRecordBackedResourcesController#destroy` already takes a block. By default the method calls `ActiveRecord::Persistence#destroy!` on the ActiveRecord instance indicated in parameters; else it'll invoke the block, passing it the record, and the block is responsible for destroying that record.

* By extension, `Scimitar::ActiveRecordBackedResourcesController#create`, `#update` and `#replace` could all likewise take a block. By default they currently call `Scimitar::ActiveRecordBackedResourcesController#save!`, passing the new/updated record; else they could invoke a block, passing the record, and the block is responsible for persisting the new or changed record given.

This seems reasonably symmetrical and allows you to deal with special cases on `#create` without needing to override `#save!` and check `ActiveRecord::Persistence#persisted?` to distinguish between create-vs-update actions. It means all write operations in the controller now behave in a similar way with an optional block that overrides the persistence action on a given record instance.

The remaining inconsistency, inherited historically, is the use of a custom and overridable `#save!` method for persistence but using `record.destroy!` to delete a record, rather than having a similar custom and overridable `#destroy` method in the controller. That'd give you two ways to tackle override, according to preference - override `#destroy` and pass a block to `super` in the implementation, or override `#destroy!`. I won't do that in the same PR to implement the above idea and might not even ever get around to it at all, since it's really just an aesthetic concern, but I felt it worth pointing out given the comments above about consistency of approach.

**Comment by pond** [comment]
It'd look like this:

```ruby
class MyController < Scimitar::ActiveRecordBackedResourcesController
  def create
    super do | record |
      # ...make any changes of interest to 'record'...
      record.save!
    end
end
```

Since `Scimitar::ActiveRecordBackedResourcesController#save!` already contains support for a block, I'll pass the block down there. This means you get its `ActiveRecord::RecordInvalid` exception handling and appropriate SCIM error rendering 'for free'.

**Comment by pond** [comment]
This'll go out in 2.7.0 - I think I can close the issue as a result?

**Comment by pond** [comment]
Taking that thumbs up as a "yes" :joy:

**Comment by pond** [comment]
This is now in [v2.7.0](https://rubygems.org/gems/scimitar/versions/2.7.0).

**Comment by pond** [comment]
...and [v1.8.0](https://rubygems.org/gems/scimitar/versions/1.8.0).
